[core]
deps_keys = [ 'dependencies', 'peerDependencies', 'devDependencies', 'docs']

[pkgset]
ignore_files = [
  '/yarn.lock',
]

[notifications.clients_common_config]
channel = '#pwa-sdet-notify'
author = { name = 'pwa-doc released!', avatarEmoji = ':pwa-doc-transparent:' }

[release_list]
enabled = true

[versioning]
source = 'tag'
