.only-master:
  only:
    - master
  except:
    refs:
      - tags
      - schedules
    variables:
      - $CI_COMMIT_MESSAGE =~ /^release/i

### INSTALL ###########################################################################################################

install-master:
  image: $NODE_IMAGE
  stage: install
  extends:
    - .only-master
  script:
    - yarn bootstrap:ci
  artifacts:
    paths:
      - node_modules
      - ./**/node_modules

### BUILD #############################################################################################################

build:create-release-tag-master:
  image: $NODE_IMAGE
  stage: build
  extends:
    - .only-master
  needs:
    - install-master
  script:
    - yarn pvm update

### CLEANUP ###########################################################################################################

notify:broken-master:
  stage: cleanup
  extends:
    - .only-master
    - .delivery-notify-broken-master
